[tool.black]
line-length = 120
skip-string-normalization = true

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]
exclude = ["esp32/venv/*", "*/__pycache__/*", "esp32/lib/*"]
per-file-ignores = "esp32/tests/*:B010"

[tool.ruff]
target-version = "py38"
line-length = 120
extend-exclude = ["esp32/lib/*", "esp32/venv/*"]

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I"]
ignore = ["E501"]  # Line too long (handled by black)

[tool.ruff.lint.per-file-ignores]
"scripts/filter_efficiency_analysis/analyze_filter_performance.py" = ["E402"]
"esp32/tests/**/*.py" = ["B010"]

[tool.ruff.lint.isort]
known-first-party = ["utils", "models", "tests", "esp32"]
relative-imports-order = "closest-to-furthest" 